import {Button} from "reactstrap"
import { useHistory } from 'react-router-dom';

// const history = useHistory();
// Custom component for the "Actions" column
const ActionsColumn = ({ row }) => {
  const history = useHistory();

  // Function to handle the view button click
  const handleView = () => {
    // Replace '/destination' with the path of the desired destination page
    history.push(`${process.env.PUBLIC_URL}/lender-organization/${row._id}`);
  };

  return (
    <Button className="btn-dim" outline color="info" onClick={handleView}>
      view
    </Button>
  );
};

export const dataTableColumns = [
  {
    name: "Name",
    selector: (row) => row.business_name,
    sortable: true,
    hide: "md",
  },
  {
    name: "Location",
    selector: (row) => row.business_location,
    sortable: true,
    hide: "md",
  },
  {
    name: "Address",
    selector: (row) => row.business_address,
    sortable: true,
    hide: "md",
  },
  {
    name: "Phone Number",
    selector: (row) => row.business_phone_number,
    sortable: true,
    hide: "md",
  },
  {
    name: "Email",
    selector: (row) => row.business_email,
    sortable: true,
    hide: "md",
  },
  {
    name: "Status",
    selector: (row) => row.status,
    sortable: true,
    hide: "md",
  },
  {
    name: "Actions",
    cell: (row) => <ActionsColumn row={row} />, // Use the custom component for rendering the "Actions" cell
    sortable: false,
    hide: "md",
  },
];

export const DataTableData = [
  {
    id: 0,
    business_name: "Francine Kirby",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 1,
    business_name: "Reva Best",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 2,
    business_name: "Alexis Flores",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 3,
    business_name: "Nixon Sullivan",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 4,
    business_name: "Foreman Wooten",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 5,
    business_name: "Franco Davis",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 6,
    business_name: "Bullock Kline",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 7,
    business_name: "Baird Coffey",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 8,
    business_name: "Eula Walters",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 9,
    business_name: "Gaines Moss",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 10,
    business_name: "Sargent Winters",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 11,
    business_name: "Sybil Patton",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 12,
    business_name: "Henderson Elliott",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 13,
    business_name: "Combs Irwin",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 14,
    business_name: "Fleming Buchanan",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 15,
    business_name: "Mcbride Dixon",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 16,
    business_name: "Nettie Greer",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 17,
    business_name: "Anita Saunders",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 18,
    business_name: "Darcy Mcclain",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 19,
    business_name: "Jodi Knowles",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 20,
    business_name: "Cathleen Schroeder",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 21,
    business_name: "Lea Fitzgerald",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 22,
    business_name: "Pitts Graham",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 23,
    business_name: "Lane Glass",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 24,
    business_name: "Tisha Cleveland",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 25,
    business_name: "Ortiz Nguyen",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 26,
    business_name: "Katrina Alvarado",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 27,
    business_name: "Craig Chang",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 28,
    business_name: "Joann Short",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 29,
    business_name: "Vargas Rivers",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 30,
    business_name: "Snow Hampton",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 31,
    business_name: "Ellison Pennington",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 32,
    business_name: "Kate Donaldson",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 33,
    business_name: "Bridges Franco",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 34,
    business_name: "Montgomery Moreno",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 35,
    business_name: "Meyers Barnett",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 36,
    business_name: "Gertrude Glenn",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 37,
    business_name: "Wise Fitzpatrick",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 38,
    business_name: "Joseph Leonard",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 39,
    business_name: "Booker Chambers",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 40,
    business_name: "Corrine Kerr",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 41,
    business_name: "Williamson Daniel",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 42,
    business_name: "Anthony Oneill",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 43,
    business_name: "Marquita Hubbard",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 44,
    business_name: "Dena Clements",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 45,
    business_name: "Tia Curry",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 46,
    business_name: "Rios House",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 47,
    business_name: "Whitfield Mcleod",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 48,
    business_name: "Conrad Holt",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
  {
    id: 49,
    business_name: "Mclaughlin Fletcher",
    business_location: "Kenya",
    business_address: "Nairobi County",
    business_phone_number: "0700000000",
    business_email: "test@gmail.com",
    contact_person: "Person name",
  },
];