export const dataTableColumns = [
  {
    name: "Business Name",
    selector: (row) => row.business_name,
    sortable: true,
  },
  {
    name: "Business Location",
    selector: (row) => row.business_location,
    sortable: true,
    hide: 370,
  },
  {
    name: "Business Address",
    selector: (row) => row.business_address,
    sortable: true,
    hide: "sm",
  },
  {
    name: "Business Phone Number",
    selector: (row) => row.business_phone_number,
    sortable: true,
    hide: "sm",
  },
  {
    name: "Business Email",
    selector: (row) => row.business_email,
    sortable: true,
    hide: "md",
  },
  {
    name: "Contact Person",
    selector: (row) => row.contact_person,
    sortable: true,
    hide: "md",
  },
];

export const DataTableData = [
  {
    id: 0,
    business_name: "Francine Kirby",
    business_location: 24,
    business_address: "female",
    business_phone_number: "BUZZWORKS",
    business_email: "2017-02-17",
    contact_person: "$2,570.39",
  },
  {
    id: 1,
    business_name: "Reva Best",
    business_location: 40,
    business_address: "female",
    business_phone_number: "MARQET",
    business_email: "2021-10-14",
    contact_person: "$1,488.76",
  },
  {
    id: 2,
    business_name: "Alexis Flores",
    business_location: 21,
    business_address: "female",
    business_phone_number: "OBONES",
    business_email: "2020-04-28",
    contact_person: "$1,336.93",
  },
  {
    id: 3,
    business_name: "Nixon Sullivan",
    business_location: 30,
    business_address: "male",
    business_phone_number: "SLUMBERIA",
    business_email: "2016-10-08",
    contact_person: "$2,156.70",
  },
  {
    id: 4,
    business_name: "Foreman Wooten",
    business_location: 20,
    business_address: "male",
    business_phone_number: "ESCENTA",
    business_email: "2018-07-12",
    contact_person: "$3,057.42",
  },
  {
    id: 5,
    business_name: "Franco Davis",
    business_location: 28,
    business_address: "male",
    business_phone_number: "ZILLACON",
    business_email: "2015-10-08",
    contact_person: "$2,730.88",
  },
  {
    id: 6,
    business_name: "Bullock Kline",
    business_location: 32,
    business_address: "male",
    business_phone_number: "SAVVY",
    business_email: "2017-07-03",
    contact_person: "$2,986.05",
  },
  {
    id: 7,
    business_name: "Baird Coffey",
    business_location: 36,
    business_address: "male",
    business_phone_number: "BLEENDOT",
    business_email: "2014-01-27",
    contact_person: "$2,755.80",
  },
  {
    id: 8,
    business_name: "Eula Walters",
    business_location: 40,
    business_address: "female",
    business_phone_number: "UXMOX",
    business_email: "2020-09-19",
    contact_person: "$3,302.75",
  },
  {
    id: 9,
    business_name: "Gaines Moss",
    business_location: 26,
    business_address: "male",
    business_phone_number: "INCUBUS",
    business_email: "2017-10-13",
    contact_person: "$3,856.24",
  },
  {
    id: 10,
    business_name: "Sargent Winters",
    business_location: 28,
    business_address: "male",
    business_phone_number: "AUSTEX",
    business_email: "2020-12-26",
    contact_person: "$3,668.64",
  },
  {
    id: 11,
    business_name: "Sybil Patton",
    business_location: 35,
    business_address: "female",
    business_phone_number: "ZILIDIUM",
    business_email: "2020-06-19",
    contact_person: "$1,987.14",
  },
  {
    id: 12,
    business_name: "Henderson Elliott",
    business_location: 39,
    business_address: "male",
    business_phone_number: "ZOARERE",
    business_email: "2016-08-16",
    contact_person: "$1,795.31",
  },
  {
    id: 13,
    business_name: "Combs Irwin",
    business_location: 33,
    business_address: "male",
    business_phone_number: "COLAIRE",
    business_email: "2017-07-19",
    contact_person: "$2,396.73",
  },
  {
    id: 14,
    business_name: "Fleming Buchanan",
    business_location: 33,
    business_address: "male",
    business_phone_number: "WEBIOTIC",
    business_email: "2021-09-12",
    contact_person: "$3,406.96",
  },
  {
    id: 15,
    business_name: "Mcbride Dixon",
    business_location: 25,
    business_address: "male",
    business_phone_number: "ZBOO",
    business_email: "2017-12-08",
    contact_person: "$1,065.32",
  },
  {
    id: 16,
    business_name: "Nettie Greer",
    business_location: 32,
    business_address: "female",
    business_phone_number: "QUONK",
    business_email: "2014-03-15",
    contact_person: "$1,558.83",
  },
  {
    id: 17,
    business_name: "Anita Saunders",
    business_location: 39,
    business_address: "female",
    business_phone_number: "IDEALIS",
    business_email: "2015-07-31",
    contact_person: "$1,848.84",
  },
  {
    id: 18,
    business_name: "Darcy Mcclain",
    business_location: 24,
    business_address: "female",
    business_phone_number: "DIGIGEN",
    business_email: "2020-02-19",
    contact_person: "$3,382.78",
  },
  {
    id: 19,
    business_name: "Jodi Knowles",
    business_location: 32,
    business_address: "female",
    business_phone_number: "KONGENE",
    business_email: "2014-03-09",
    contact_person: "$1,668.05",
  },
  {
    id: 20,
    business_name: "Cathleen Schroeder",
    business_location: 21,
    business_address: "female",
    business_phone_number: "TROPOLIS",
    business_email: "2014-09-28",
    contact_person: "$2,730.21",
  },
  {
    id: 21,
    business_name: "Lea Fitzgerald",
    business_location: 24,
    business_address: "female",
    business_phone_number: "AVENETRO",
    business_email: "2015-08-17",
    contact_person: "$2,547.85",
  },
  {
    id: 22,
    business_name: "Pitts Graham",
    business_location: 20,
    business_address: "male",
    business_phone_number: "MALATHION",
    business_email: "2020-05-08",
    contact_person: "$3,538.05",
  },
  {
    id: 23,
    business_name: "Lane Glass",
    business_location: 22,
    business_address: "male",
    business_phone_number: "NETROPIC",
    business_email: "2020-01-26",
    contact_person: "$1,141.42",
  },
  {
    id: 24,
    business_name: "Tisha Cleveland",
    business_location: 33,
    business_address: "female",
    business_phone_number: "YURTURE",
    business_email: "2020-01-11",
    contact_person: "$2,877.89",
  },
  {
    id: 25,
    business_name: "Ortiz Nguyen",
    business_location: 34,
    business_address: "male",
    business_phone_number: "TRIBALOG",
    business_email: "2019-07-09",
    contact_person: "$3,156.79",
  },
  {
    id: 26,
    business_name: "Katrina Alvarado",
    business_location: 33,
    business_address: "female",
    business_phone_number: "PYRAMIA",
    business_email: "2016-07-04",
    contact_person: "$2,273.02",
  },
  {
    id: 27,
    business_name: "Craig Chang",
    business_location: 30,
    business_address: "male",
    business_phone_number: "COMVEYER",
    business_email: "2019-09-08",
    contact_person: "$3,028.17",
  },
  {
    id: 28,
    business_name: "Joann Short",
    business_location: 30,
    business_address: "female",
    business_phone_number: "PRISMATIC",
    business_email: "2017-08-17",
    contact_person: "$2,041.14",
  },
  {
    id: 29,
    business_name: "Vargas Rivers",
    business_location: 23,
    business_address: "male",
    business_phone_number: "ELPRO",
    business_email: "2014-04-25",
    contact_person: "$1,906.04",
  },
  {
    id: 30,
    business_name: "Snow Hampton",
    business_location: 37,
    business_address: "male",
    business_phone_number: "SNORUS",
    business_email: "2014-11-30",
    contact_person: "$1,419.30",
  },
  {
    id: 31,
    business_name: "Ellison Pennington",
    business_location: 32,
    business_address: "male",
    business_phone_number: "APEX",
    business_email: "2020-02-06",
    contact_person: "$3,486.62",
  },
  {
    id: 32,
    business_name: "Kate Donaldson",
    business_location: 28,
    business_address: "female",
    business_phone_number: "TALENDULA",
    business_email: "2021-07-05",
    contact_person: "$3,025.63",
  },
  {
    id: 33,
    business_name: "Bridges Franco",
    business_location: 20,
    business_address: "male",
    business_phone_number: "FURNAFIX",
    business_email: "2021-09-21",
    contact_person: "$1,371.72",
  },
  {
    id: 34,
    business_name: "Montgomery Moreno",
    business_location: 24,
    business_address: "male",
    business_phone_number: "ZIORE",
    business_email: "2018-08-04",
    contact_person: "$1,016.90",
  },
  {
    id: 35,
    business_name: "Meyers Barnett",
    business_location: 25,
    business_address: "male",
    business_phone_number: "OCEANICA",
    business_email: "2017-03-04",
    contact_person: "$3,804.05",
  },
  {
    id: 36,
    business_name: "Gertrude Glenn",
    business_location: 29,
    business_address: "female",
    business_phone_number: "FORTEAN",
    business_email: "2018-04-19",
    contact_person: "$3,883.97",
  },
  {
    id: 37,
    business_name: "Wise Fitzpatrick",
    business_location: 34,
    business_address: "male",
    business_phone_number: "RODEOLOGY",
    business_email: "2017-11-08",
    contact_person: "$1,400.23",
  },
  {
    id: 38,
    business_name: "Joseph Leonard",
    business_location: 30,
    business_address: "male",
    business_phone_number: "QIMONK",
    business_email: "2014-12-01",
    contact_person: "$2,689.09",
  },
  {
    id: 39,
    business_name: "Booker Chambers",
    business_location: 24,
    business_address: "male",
    business_phone_number: "SKYPLEX",
    business_email: "2014-07-29",
    contact_person: "$3,949.05",
  },
  {
    id: 40,
    business_name: "Corrine Kerr",
    business_location: 35,
    business_address: "female",
    business_phone_number: "FIBEROX",
    business_email: "2019-06-07",
    contact_person: "$2,245.15",
  },
  {
    id: 41,
    business_name: "Williamson Daniel",
    business_location: 26,
    business_address: "male",
    business_phone_number: "GREEKER",
    business_email: "2020-09-15",
    contact_person: "$3,814.20",
  },
  {
    id: 42,
    business_name: "Anthony Oneill",
    business_location: 36,
    business_address: "male",
    business_phone_number: "MIXERS",
    business_email: "2020-07-22",
    contact_person: "$1,129.99",
  },
  {
    id: 43,
    business_name: "Marquita Hubbard",
    business_location: 25,
    business_address: "female",
    business_phone_number: "VELOS",
    business_email: "2015-11-19",
    contact_person: "$2,227.39",
  },
  {
    id: 44,
    business_name: "Dena Clements",
    business_location: 34,
    business_address: "female",
    business_phone_number: "ORBEAN",
    business_email: "2020-08-31",
    contact_person: "$2,689.21",
  },
  {
    id: 45,
    business_name: "Tia Curry",
    business_location: 37,
    business_address: "female",
    business_phone_number: "MUSAPHICS",
    business_email: "2019-04-02",
    contact_person: "$3,784.72",
  },
  {
    id: 46,
    business_name: "Rios House",
    business_location: 30,
    business_address: "male",
    business_phone_number: "IMPERIUM",
    business_email: "2015-08-23",
    contact_person: "$1,519.37",
  },
  {
    id: 47,
    business_name: "Whitfield Mcleod",
    business_location: 37,
    business_address: "male",
    business_phone_number: "SCHOOLIO",
    business_email: "2015-03-17",
    contact_person: "$2,365.21",
  },
  {
    id: 48,
    business_name: "Conrad Holt",
    business_location: 38,
    business_address: "male",
    business_phone_number: "MENBRAIN",
    business_email: "2020-02-01",
    contact_person: "$2,289.04",
  },
  {
    id: 49,
    business_name: "Mclaughlin Fletcher",
    business_location: 34,
    business_address: "male",
    business_phone_number: "SOLAREN",
    business_email: "2018-09-05",
    contact_person: "$1,115.62",
  },
];